/*
Currently, macOS backend is mostly generated by Gemini 3 Pro.
I do not wish to touch Objective-C as much as the next person.
If someone more experienced in Obj-C/Swift wants to refactor this,
please do so.
*/
#import <Foundation/Foundation.h>
#import <IOBluetooth/IOBluetooth.h>
#include <deque>
#include <vector>
#include <mutex>
#include <string>

#include "../Platform.hpp"
#include <mdr-c/Platform/PlatformMacOS.h>

@interface MDRBluetoothDelegate : NSObject <IOBluetoothRFCOMMChannelDelegate>
@property (nonatomic, strong) IOBluetoothRFCOMMChannel *rfcommChannel;
@property (nonatomic, strong) NSMutableData *buffer;
@property (nonatomic, assign) BOOL isConnected;
@property (nonatomic, assign) BOOL isConnecting;
@property (nonatomic, strong) NSString *lastError;

- (void)appendData:(NSData *)data;
- (NSData *)readData:(NSUInteger)maxLength;
- (void)connectToAddress:(NSString *)address serviceUUID:(NSString *)uuid;
- (void)disconnect;
- (void)sendData:(NSData *)data;
@end

@implementation MDRBluetoothDelegate
{
    std::mutex _bufferMutex;
}

- (instancetype)init {
    self = [super init];
    if (self) {
        _buffer = [NSMutableData data];
        _isConnected = NO;
        _isConnecting = NO;
    }
    return self;
}

- (void)appendData:(NSData *)data {
    std::lock_guard<std::mutex> lock(_bufferMutex);
    [_buffer appendData:data];
}

- (NSData *)readData:(NSUInteger)maxLength {
    std::lock_guard<std::mutex> lock(_bufferMutex);
    if (_buffer.length == 0) {
        return nil;
    }
    
    NSUInteger len = MIN(maxLength, _buffer.length);
    NSData *subData = [_buffer subdataWithRange:NSMakeRange(0, len)];
    
    // Efficiently remove head? NSMutableData replaceBytes might be slow-ish but fine for small buffers
    [_buffer replaceBytesInRange:NSMakeRange(0, len) withBytes:NULL length:0];
    return subData;
}

- (void)connectToAddress:(NSString *)address serviceUUID:(NSString *)uuidString {
    self.isConnecting = YES;
    self.lastError = nil;
    
    // Address format fix: IOBluetooth expects XX-XX-XX-XX-XX-XX sometimes or XX:XX... 
    // addressString property returns dashes. deviceWithAddressString handles both usually.
    IOBluetoothDevice *device = [IOBluetoothDevice deviceWithAddressString:address];
    if (!device) {
        self.lastError = @"Device not found (not paired?)";
        self.isConnecting = NO;
        return;
    }
    
    // We need to resolve the service channel for the custom UUID.
    // Ensure we have SDP records.
    // This is synchronous if we assume cached, but cleaner to perform SDP query if needed.
    // For now assuming paired device has records available.
    
    uint8_t uuidBytes[16];
    if (serviceUUIDtoBytes([uuidString UTF8String], uuidBytes) != 0) {
        self.lastError = @"Invalid UUID string";
        self.isConnecting = NO;
        return;
    }

    IOBluetoothSDPUUID *uuid = [IOBluetoothSDPUUID uuidWithBytes:uuidBytes length:16];
    IOBluetoothSDPServiceRecord *serviceRecord = [device getServiceRecordForUUID:uuid];
    
    if (!serviceRecord) {
        self.lastError = @"Service not found on device (try checking Bluetooth settings/ensure paired)";
        self.isConnecting = NO;
        return;
    }
    
    BluetoothRFCOMMChannelID channelID;
    if ([serviceRecord getRFCOMMChannelID:&channelID] != kIOReturnSuccess) {
        self.lastError = @"Could not get RFCOMM Channel ID from service record";
        self.isConnecting = NO;
        return;
    }
    
    IOBluetoothRFCOMMChannel *channel = nil;
    // Async open
    IOReturn result = [device openRFCOMMChannelAsync:&channel withChannelID:channelID delegate:self];
    
    if (result != kIOReturnSuccess) {
        self.lastError = [NSString stringWithFormat:@"Failed to open RFCOMM channel: 0x%x", result];
        self.isConnecting = NO;
        return;
    }
    
    self.rfcommChannel = channel;
}

- (void)disconnect {
    if (self.rfcommChannel) {
        // [self.rfcommChannel closeChannel]; // closeChannel is valid?
        // documentation says closeChannel.
        [self.rfcommChannel closeChannel];
        self.rfcommChannel = nil;
    }
    self.isConnected = NO;
    self.isConnecting = NO;
}

- (void)sendData:(NSData *)data {
    if (self.rfcommChannel && self.isConnected) {
        // writeAsync is best effort and non-blocking
        [self.rfcommChannel writeAsync:(void *)data.bytes length:data.length refcon:NULL];
    }
}

// IOBluetoothRFCOMMChannelDelegate methods

- (void)rfcommChannelOpenComplete:(IOBluetoothRFCOMMChannel *)rfcommChannel status:(IOReturn)error {
    if (error != kIOReturnSuccess) {
        self.lastError = [NSString stringWithFormat:@"Connection handshake failed: 0x%x", error];
        self.isConnecting = NO;
        self.isConnected = NO;
        self.rfcommChannel = nil; // clear it
        return;
    }
    self.isConnected = YES;
    self.isConnecting = NO;
}

- (void)rfcommChannelData:(IOBluetoothRFCOMMChannel *)rfcommChannel data:(void *)dataPointer length:(size_t)dataLength {
    NSData *data = [NSData dataWithBytes:dataPointer length:dataLength];
    [self appendData:data];
}

- (void)rfcommChannelClosed:(IOBluetoothRFCOMMChannel *)rfcommChannel {
    self.isConnected = NO;
    self.isConnecting = NO;
    self.rfcommChannel = nil;
    if (!self.lastError) {
        self.lastError = @"Connection closed by remote";
    }
}

@end

struct MDRConnectionMacOS
{
    MDRConnection mdrConn;
    MDRBluetoothDelegate *delegate;
    
    MDRConnectionMacOS() {
        delegate = [[MDRBluetoothDelegate alloc] init];
        mdrConn = {
            .user = this,
            .connect = Connect,
            .disconnect = Disconnect,
            .recv = Recv,
            .send = Send,
            .poll = Poll,
            .getDevicesList = GetDevicesList,
            .freeDevicesList = FreeDevicesList,
            .getLastError = GetLastError
        };
    }
    
    ~MDRConnectionMacOS() {
        // Delegate is autoreleased or we rely on ARC.
        // If we want to clean up strictly:
        [delegate disconnect];
        delegate = nil;
    }

    static int Connect(void* user, const char* macAddress, const char* serviceUUID) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            NSString *addrParams = [NSString stringWithUTF8String:macAddress];
            NSString *uuidParams = [NSString stringWithUTF8String:serviceUUID];
            
            [self->delegate connectToAddress:addrParams serviceUUID:uuidParams];
            
            if (self->delegate.lastError && !self->delegate.isConnecting) {
                return MDR_RESULT_ERROR_NET;
            }
            return MDR_RESULT_INPROGRESS;
        }
    }

    static void Disconnect(void* user) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            [self->delegate disconnect];
        }
    }

    static int Recv(void* user, char* dst, int size, int* pReceived) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            if (!self->delegate.isConnected) {
                return MDR_RESULT_ERROR_NO_CONNECTION;
            }
            
            NSData *data = [self->delegate readData:size];
            if (data && data.length > 0) {
                memcpy(dst, data.bytes, data.length);
                *pReceived = (int)data.length;
                return MDR_RESULT_OK;
            }
            return MDR_RESULT_INPROGRESS; 
        }
    }

    static int Send(void* user, const char* src, int size, int* pSent) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            if (!self->delegate.isConnected) {
                return MDR_RESULT_ERROR_NO_CONNECTION;
            }
            NSData *data = [NSData dataWithBytes:src length:size];
            [self->delegate sendData:data];
            *pSent = size;
            return MDR_RESULT_OK;
        }
    }

    static int Poll(void* user, int timeout) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        @autoreleasepool {
            // Processing run loop events
            // We use a small interval if timeout > 0, otherwise instant check?
            // If timeout is 0, we should just check and return immediately?
            // Use 0.001s minimum to allow runloop to turn if timeout > 0
            
            if (timeout < 0) timeout = 1000; // Cap infinite wait for now or loop?
            
            double seconds = timeout / 1000.0;
            if (seconds <= 0) seconds = 0.0001; 
            
            NSDate *limitDate = [NSDate dateWithTimeIntervalSinceNow:seconds];
            [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:limitDate];
            
            if (self->delegate.lastError && !self->delegate.isConnected && !self->delegate.isConnecting) {
                // Determine if it was a connection error or query error
                // For Poll(), if we are waiting for connection
                return MDR_RESULT_ERROR_NET;
            }
            
            if (self->delegate.isConnected) {
                return MDR_RESULT_OK;
            }
            
            if (self->delegate.isConnecting) {
                // If timeout reached and still connecting...
                // The caller typically calls poll in a loop until OK or Error.
                // So returning INPROGRESS is correct if time expired but no error yet.
                return MDR_RESULT_INPROGRESS; 
            }
            
            return MDR_RESULT_ERROR_NET;
        }
    }

    static int GetDevicesList(void* user, MDRDeviceInfo** ppList, int* pCount) {
        @autoreleasepool {
            NSArray *devices = [IOBluetoothDevice pairedDevices];
            if (!devices || devices.count == 0) {
                *pCount = 0;
                *ppList = nullptr;
                return MDR_RESULT_OK;
            }
            
            *ppList = new MDRDeviceInfo[devices.count];
            *pCount = (int)devices.count;
            
            for (NSUInteger i = 0; i < devices.count; i++) {
                IOBluetoothDevice *dev = devices[i];
                NSString *name = dev.name;
                NSString *addr = [dev.addressString stringByReplacingOccurrencesOfString:@"-" withString:@":"];
                
                MDRDeviceInfo *info = &(*ppList)[i];
                memset(info, 0, sizeof(MDRDeviceInfo));
                
                if (name) {
                    strncpy(info->szDeviceName, [name UTF8String], sizeof(info->szDeviceName) - 1);
                }
                if (addr) {
                    strncpy(info->szDeviceMacAddress, [addr UTF8String], sizeof(info->szDeviceMacAddress) - 1);
                }
            }
            return MDR_RESULT_OK;
        }
    }
    
    static int FreeDevicesList(void* user, MDRDeviceInfo** ppList) {
        if (*ppList)
        {
            delete[] *ppList;
            *ppList = nullptr;
        }
        return MDR_RESULT_OK;
    }
    
    static const char* GetLastError(void* user) {
        auto* self = static_cast<MDRConnectionMacOS*>(user);
        if (self->delegate.lastError) {
             // Returning a temporary pointer is risky if ARC deallocates the string/autorelease pool drains?
             // But UTF8String returns inner pointer of const char.
             // We can duplicate it, or rely on caller copying it implicitly?
             // MDRConnection contract says "get last error".
             // We should better copy it to a buffer in the struct.
             return [self->delegate.lastError UTF8String];
        }
        return "";
    }
};

MDRConnectionMacOS* mdrConnectionMacOSCreate() { return new MDRConnectionMacOS(); }
MDRConnection* mdrConnectionMacOSGet(MDRConnectionMacOS* self) { return &self->mdrConn; }
void mdrConnectionMacOSDestroy(MDRConnectionMacOS* self) { delete self; }
