import Foundation

// T1 enums from ProtocolV2T1.hpp
// Namespace: mdr::v2::t1


public enum ConnectInquiredType: UInt8, Sendable {
    case FIXED_VALUE = 0
}

public enum DeviceInfoType: UInt8, Sendable {
    case MODEL_NAME = 1
    case FW_VERSION = 2
    case SERIES_AND_COLOR_INFO = 3
    case INSTRUCTION_GUIDE = 4
}

public enum ModelColor: UInt8, Sendable {
    case DEFAULT = 0
    case BLACK = 1
    case WHITE = 2
    case SILVER = 3
    case RED = 4
    case BLUE = 5
    case PINK = 6
    case YELLOW = 7
    case GREEN = 8
    case GRAY = 9
    case GOLD = 10
    case CREAM = 11
    case ORANGE = 12
    case BROWN = 13
    case VIOLET = 14
}

public enum ModelSeriesType: UInt8, Sendable {
    case NO_SERIES = 0
    case EXTRA_BASS = 0x10
    case ULT_POWER_SOUND = 0x11
    case HEAR = 0x20
    case PREMIUM = 0x30
    case SPORTS = 0x40
    case CASUAL = 0x50
    case LINK_BUDS = 0x60
    case NECKBAND = 0x70
    case LINKPOD = 0x80
    case GAMING = 0x90
}

public enum CommonInquiredType: UInt8, Sendable {
    case CONCIERGE = 0x00
    case CONNECTION_STATUS = 0x01
    case AUDIO_CODEC = 0x02
    case UPSCALING_EFFECT = 0x03
    case BLE_SETUP = 0x04
    case CONNECTION_ESTABLISHED_TIME = 0x05
    case DEVICE_SPECIAL_MODE = 0x06
    case SMART_PHONE_AND_CONNECTED_DEVICE_INFORMATION_FOR_CLASSIC = 0x07
    case TANDEM_RECONNECTION_REQUEST = 0x08
    case DISPLAY_FW_VERSION = 0x09
}

public enum AudioCodec: UInt8, Sendable {
    case UNSETTLED = 0x00
    case SBC = 0x01
    case AAC = 0x02
    case LDAC = 0x10
    case APT_X = 0x20
    case APT_X_HD = 0x21
    case LC3 = 0x30
    case OTHER = 0xFF
}

public enum PowerInquiredType: UInt8, Sendable {
    case BATTERY = 0x00
    case LEFT_RIGHT_BATTERY = 0x01
    case CRADLE_BATTERY = 0x02
    case POWER_OFF = 0x03
    case AUTO_POWER_OFF = 0x04
    case AUTO_POWER_OFF_WEARING_DETECTION = 0x05
    case POWER_SAVE_MODE = 0x06
    case LINK_CONTROL = 0x07
    case BATTERY_WITH_THRESHOLD = 0x08
    case LR_BATTERY_WITH_THRESHOLD = 0x09
    case CRADLE_BATTERY_WITH_THRESHOLD = 0x0A
    case BATTERY_SAFE_MODE = 0x0B
    case CARING_CHARGE = 0x0C
    case BT_STANDBY = 0x0D
    case STAMINA = 0x0E
    case AUTOMATIC_TOUCH_PANEL_BACKLIGHT_TURN_OFF = 0x0F
}

public enum BatteryChargingStatus: UInt8, Sendable {
    case NOT_CHARGING = 0
    case CHARGING = 1
    case UNKNOWN = 2
    case CHARGED = 3
}

public enum PowerOffSettingValue: UInt8, Sendable {
    case USER_POWER_OFF = 0x01
    case FACTORY_POWER_OFF = 0xFF
}

public enum AutoPowerOffElements: UInt8, Sendable {
    case POWER_OFF_IN_5_MIN = 0x00
    case POWER_OFF_IN_30_MIN = 0x01
    case POWER_OFF_IN_60_MIN = 0x02
    case POWER_OFF_IN_180_MIN = 0x03
    case POWER_OFF_IN_15_MIN = 0x04
    case POWER_OFF_DISABLE = 0x11
}

public enum AutoPowerOffWearingDetectionElements: UInt8, Sendable {
    case POWER_OFF_IN_5_MIN = 0x00
    case POWER_OFF_IN_30_MIN = 0x01
    case POWER_OFF_IN_60_MIN = 0x02
    case POWER_OFF_IN_180_MIN = 0x03
    case POWER_OFF_IN_15_MIN = 0x04
    case POWER_OFF_WHEN_REMOVED_FROM_EARS = 0x10
    case POWER_OFF_DISABLE = 0x11
}

public enum EqEbbInquiredType: UInt8, Sendable {
    case PRESET_EQ = 0x00
    case EBB = 0x01
    case PRESET_EQ_NONCUSTOMIZABLE = 0x02
    case PRESET_EQ_AND_ULT_MODE = 0x03
    case PRESET_EQ_AND_ERRORCODE = 0x04
    case SOUND_EFFECT = 0x30
    case CUSTOM_EQ = 0x31
    case TURN_KEY_EQ = 0x32
}

public enum EqPresetId: UInt8, Sendable {
    case OFF = 0x00
    case ROCK = 0x01
    case POP = 0x02
    case JAZZ = 0x03
    case DANCE = 0x04
    case EDM = 0x05
    case R_AND_B_HIP_HOP = 0x06
    case ACOUSTIC = 0x07
    case RESERVED_FOR_FUTURE_NO8 = 0x08
    case RESERVED_FOR_FUTURE_NO9 = 0x09
    case RESERVED_FOR_FUTURE_NO10 = 0x0A
    case RESERVED_FOR_FUTURE_NO11 = 0x0B
    case RESERVED_FOR_FUTURE_NO12 = 0x0C
    case RESERVED_FOR_FUTURE_NO13 = 0x0D
    case RESERVED_FOR_FUTURE_NO14 = 0x0E
    case RESERVED_FOR_FUTURE_NO15 = 0x0F
    case BRIGHT = 0x10
    case EXCITED = 0x11
    case MELLOW = 0x12
    case RELAXED = 0x13
    case VOCAL = 0x14
    case TREBLE = 0x15
    case BASS = 0x16
    case SPEECH = 0x17
    case RESERVED_FOR_FUTURE_NO24 = 0x18
    case RESERVED_FOR_FUTURE_NO25 = 0x19
    case RESERVED_FOR_FUTURE_NO26 = 0x1A
    case RESERVED_FOR_FUTURE_NO27 = 0x1B
    case RESERVED_FOR_FUTURE_NO28 = 0x1C
    case RESERVED_FOR_FUTURE_NO29 = 0x1D
    case RESERVED_FOR_FUTURE_NO30 = 0x1E
    case RESERVED_FOR_FUTURE_NO31 = 0x1F
    case GAMING_EQ = 0x20
    case FPS_1 = 0x21
    case FPS_2 = 0x22
    case FPS_3 = 0x23
    case HEAVY = 0x30
    case CLEAR = 0x31
    case HARD = 0x32
    case SOFT = 0x33
    case CUSTOM = 0xA0
    case USER_SETTING1 = 0xA1
    case USER_SETTING2 = 0xA2
    case USER_SETTING3 = 0xA3
    case USER_SETTING4 = 0xA4
    case USER_SETTING5 = 0xA5
    case ARTIST_COLLAB1 = 0xB0
    case ARTIST_COLLAB2 = 0xB1
    case ARTIST_COLLAB3 = 0xB2
    case ARTIST_COLLAB4 = 0xB3
    case ARTIST_COLLAB5 = 0xB4
    case ARTIST_COLLAB6 = 0xB5
    case ARTIST_COLLAB7 = 0xB6
    case ARTIST_COLLAB8 = 0xB7
    case ARTIST_COLLAB9 = 0xB8
    case ARTIST_COLLAB10 = 0xB9
    case ARTIST_COLLAB11 = 0xBA
    case ARTIST_COLLAB12 = 0xBB
    case UNSPECIFIED = 0xFF
}

public enum EqUltMode: UInt8, Sendable {
    case OFF = 0x00
    case ULT_1 = 0x01
    case ULT_2 = 0x02
}

public enum SoundEffectType: UInt8, Sendable {
    case SOUND_EFFECT_OFF = 0x00
    case SOUND_EFFECT_ULT = 0x01
    case SOUND_EFFECT_ULT1 = 0x02
    case SOUND_EFFECT_ULT2 = 0x03
    case SOUND_EFFECT_CUSTOM = 0x04
    case SOUND_EFFECT_NONE = 0xFF
}

public enum PresetEqErrorCodeType: UInt8, Sendable {
    case CALLING = 0x00
    case DEMO_MODE = 0x01
    case LISTENING_MODE = 0x02
    case OTHER = 0xFE
}

public enum NcAsmInquiredType: UInt8, Sendable {
    case NC_ON_OFF = 0x1
    case NC_ON_OFF_AND_ASM_ON_OFF = 0x11
    case NC_MODE_SWITCH_AND_ASM_ON_OFF = 0x12
    case NC_ON_OFF_AND_ASM_SEAMLESS = 0x13
    case NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x14
    case MODE_NC_ASM_AUTO_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x15
    case MODE_NC_ASM_DUAL_SINGLE_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x16
    case MODE_NC_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x17
    case MODE_NC_NCSS_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 0x18
    case MODE_NC_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS_NA = 0x19
    case ASM_ON_OFF = 0x21
    case ASM_SEAMLESS = 0x22
    case NC_AMB_TOGGLE = 0x30
    case NC_TEST_MODE = 0x40
}

public enum ValueChangeStatus: UInt8, Sendable {
    case UNDER_CHANGING = 0
    case CHANGED = 1
}

public enum NcAsmOnOffValue: UInt8, Sendable {
    case OFF = 0
    case ON = 1
}

public enum NcAsmMode: UInt8, Sendable {
    case NC = 0
    case ASM = 1
}

public enum AmbientSoundMode: UInt8, Sendable {
    case NORMAL = 0
    case VOICE = 1
}

public enum NoiseAdaptiveSensitivity: UInt8, Sendable {
    case STANDARD = 0
    case HIGH = 1
    case LOW = 2
}

public enum Function: UInt8, Sendable {
    case NO_FUNCTION = 0x00
    case NC_ASM_OFF = 0x01
    case NC_ASM = 0x02
    case NC_OFF = 0x03
    case ASM_OFF = 0x04
    case QUICK_ATTENTION = 0x10
    case NC_OPTIMIZER = 0x11
    case PLAY_PAUSE = 0x20
    case NEXT_TRACK = 0x21
    case PREV_TRACK = 0x22
    case VOLUME_UP = 0x23
    case VOLUME_DOWN = 0x24
    case VOICE_RECOGNITION = 0x30
    case GET_YOUR_NOTIFICATION = 0x31
    case TALK_TO_GOOGLE_ASSISTANT = 0x32
    case STOP_GOOGLE_ASSISTANT = 0x33
    case VOICE_INPUT_CANCEL = 0x34
    case TALK_TO_TENCENT_XIAOWEI = 0x35
    case CANCEL_VOICE_RECOGNITION = 0x36
    case VOICE_INPUT_AMAZON_ALEXA = 0x37
    case CANCEL_AMAZON_ALEXA = 0x38
    case CANCEL_TENCENT_XIAOWEI = 0x39
    case LAUNCH_MLP = 0x40
    case TALK_TO_YOUR_MLP = 0x41
    case SPTF_ONE_TOUCH = 0x42
    case QUICK_ACCESS1 = 0x43
    case QUICK_ACCESS2 = 0x44
    case TALK_TO_TENCENT_XIAOWEI_CANCEL = 0x45
    case Q_MSC_ONE_TOUCH = 0x46
    case TEAMS = 0x47
    case TEAMS_VOICE_SKILLS = 0x48
    case NC_NCSS_ASM_OFF = 0x50
    case NC_NCSS_ASM = 0x51
    case NC_NCSS_OFF = 0x52
    case NCSS_ASM_OFF = 0x53
    case NC_NCSS = 0x54
    case NCSS_ASM = 0x55
    case NCSS_OFF = 0x56
    case AMB_SETTING = 0x57
    case STANDARD_VOICE_SOUND = 0x58
    case MIC_MUTE = 0x70
    case GAME_UP = 0x71
    case CHAT_UP = 0x72
}

public enum AlertInquiredType: UInt8, Sendable {
    case FIXED_MESSAGE = 0x00
    case VIBRATOR_ALERT_NOTIFICATION = 0x01
    case FIXED_MESSAGE_WITH_LEFT_RIGHT_SELECTION = 0x02
    case VOICE_ASSISTANT_ALERT_NOTIFICATION = 0x03
    case APP_BECOMES_FOREGROUND = 0x04
    case LE_AUDIO_ALERT_NOTIFICATION = 0x05
    case FLEXIBLE_MESSAGE = 0x06
}

public enum AlertMessageType: UInt8, Sendable {
    case DISCONNECT_CAUSED_BY_CONNECTION_MODE_CHANGE = 0x00
    case DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN = 0x01
    case NEED_DISCONNECTION_FOR_UPDATING_FIRMWARE = 0x02
    case GOOGLE_ASSISTANT_IS_NOW_AVAILABLE = 0x03
    case DUAL_ASSIGN_OF_VOICE_ASSISTANT_IS_UNAVAILABLE = 0x05
    case DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT_LDAC_DISABLE = 0x06
    case DISCONNECT_CAUSED_BY_CHANGING_MULTIPOINT = 0x07
    case BATTERY_CONSUMPTION_INCREASE_DUE_TO_EQ_AND_UPSCALING = 0x08
    case CAUTION_FOR_DUAL_ASSIGNMENT_OF_PLAYBACK_CONTROL = 0x09
    case CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL = 0x0A
    case CAUTION_FOR_DISABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION = 0x0B
    case CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL = 0x0C
    case CAUTION_FOR_ABLE_TOUCH_SENSOR_PANEL_AND_RECONNECTION = 0x0D
    case CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON = 0x0E
    case CAUTION_FOR_DISABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR = 0x0F
    case CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON = 0x10
    case CAUTION_FOR_DISABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR = 0x11
    case CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON = 0x12
    case CAUTION_FOR_ABLE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR = 0x13
    case CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_BUTTON = 0x14
    case CAUTION_FOR_ABLE_VOICE_ASSISTANT_AND_RECONNECTION_ASSIGNABLE_SENSOR = 0x15
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT = 0x16
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL = 0x17
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_TOUCH_SENSOR_PANEL_MOBILE_OR_SIRI = 0x18
    case FOREGROUND_CAUTION_NEED_DISCONNECTION_FOR_ENABLING_WAKE_WORD = 0x19
    case FOREGROUND_CAUTION_WAKE_WORD_IS_AVAILABLE_ONLY_IN_USE_OF_ALEXA = 0x1A
    case CAUTION_FOR_NOT_CONNECTED_COMPASS_MOUNTING_SIDE_RIGHT = 0x1B
    case CAUTION_FOR_CONNECTION_MODE_SOUND_QUALITY_PRIOR = 0x1C
    case CAUTION_FOR_FW_UPDATE_IN_PROGRESS = 0x1D
    case CAUTION_FOR_DISABLE_SAR_GM1 = 0x1E
    case CAUTION_FOR_GATT_DISCONNECTION_FOR_SAR = 0x1F
    case CAUTION_FOR_GATT_TO_ON = 0x20
    case CANT_ASSIGN_MS_AND_GOOGLE_ASSISTANT_AT_THE_SAME_TIME = 0x21
    case CAUTION_FOR_GATT_FOR_MS = 0x22
    case CAUTION_FOR_GATT_FOR_QUICK_ACCESS_SERVICE = 0x23
    case DISCONNECT_CAUSED_BY_GATT_ON = 0x24
    case DISCONNECT_AND_CHANGE_KEY_ASSIGN_CAUSED_BY_GATT_ON = 0x25
    case DISCONNECT_CAUSED_BY_CHANGING_KEY_ASSIGN_AND_CHANGE_GATT_TO_OFF = 0x26
    case DISCONNECT_CAUSED_BY_CHANGING_VOICE_ASSISTANT_AND_CHANGE_GATT_TO_OFF = 0x27
    case DISCONNECT_AND_CHANGE_VOICE_ASSISTANT_TO_SIRI_CAUSED_BY_GATT_ON = 0x28
    case CANT_USE_LDAC_WHILE_GATT_IS_ON = 0x29
    case CANT_USE_LDAC_IN_SOUND_QUALITY_PRIOR = 0x2A
    case BATTERY_CONSUMPTION_INCREASE_DUE_TO_SOUND_FUNCTION_1 = 0x2B
    case DISCONNECT_CAUSED_BY_CHANGING_CONNECTION_STANDBY_MODE_CLASSIC_ONLY = 0x2C
    case DISCONNECT_CAUSED_BY_CHANGING_CONNECTION_STANDBY_MODE_LE_AUDIO_CLASSIC = 0x2D
    case DISCONNECT_CAUSED_BY_ENTER_PAIRING_MODE_CLASSIC = 0x2E
    case DISCONNECT_CAUSED_BY_ENTER_PAIRING_MODE_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE = 0x2F
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_CLASSIC = 0x30
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE = 0x31
    case BISTO_LCH_ASSIGNMENT_AND_GATT_ACTIVATION_IS_IMPOSSIBLE = 0x32
    case TEAMS_MUST_BE_ASSIGNED_TO_EITHER_LEFT_OR_RIGHT = 0x33
    case DISCONNECT_CAUSED_BY_ENTER_PAIRING_MODE_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE_PDM = 0x36
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE_PDM = 0x37
    case DISCONNECT_CAUSED_BY_ENTER_PAIRING_MODE_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE_QA = 0x38
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE_QA = 0x39
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION_VAS_CONNECTION_MODE_QA_PDM = 0x41
    case CANT_USE_LDAC_WHILE_GATT_IS_ON_NO_RIGHT_SIDE_LIMITATION = 0x50
    case CAUTION_FOR_CHANGING_VOICE_ASSISTANT_TO_SIRI = 0x51
    case CAUTION_FOR_GATT_TO_OFF_CAUSED_BY_CHANGING_VOICE_ASSISTANT = 0x52
    case CAUTION_FOR_LDAC_990 = 0x53
    case CAUTION_FOR_GATT_TO_ON_FOR_QA_EASY_SETTING = 0x54
    case CAUTION_FOR_FW_UPDATE_IN_PROGRESS_FOR_QA_EASY_SETTING = 0x55
    case DISCONNECT_CAUSED_BY_GATT_ON_FOR_EASY_SETTING = 0x56
    case DISCONNECT_AND_CHANGE_KEY_ASSIGN_CAUSED_BY_GATT_ON_FOR_QA_EASY_SETTING = 0x57
    case DISCONNECT_AND_CHANGE_VOICE_ASSISTANT_TO_SIRI_CAUSED_BY_GATT_ON_FOR_QA_EASY_SETTING = 0x58
    case CAUTION_FOR_AUTO_VOLUME_OPTIMIZER_TO_ON = 0x59
    case CAUTION_FOR_AUTO_VOLUME_TO_ON_SVC_IS_ON = 0x5A
    case CAUTION_FOR_AUTO_VOLUME_TO_ON_SVC_VOLUME_LIMITATION_IS_ON = 0x5B
    case CAUTION_FOR_EXCLUSIVE_EQ_CHANGING_AND_BGM_MODE = 0x5C
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_OTHER_VOICE_ASSISTANT = 0x5D
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_PLAYBACK_CONTROL_L = 0x5E
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_PLAYBACK_CONTROL_R = 0x5F
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_NC_ASM_QUICK_ACCESS_L = 0x60
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_NC_ASM_QUICK_ACCESS_R = 0x61
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_VOICE_ASSISTANT_TO_NOT_SVA = 0x62
    case CAUTION_FOR_CAN_USE_GOOGLE_HOT_WORD = 0x63
    case CAUTION_FOR_CALLING_WHEN_SVA_TRAINING = 0x64
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_BE_ENABLE_REPEAT_TAP = 0x65
    case CAUTION_FOR_CHANGE_KEY_ASSIGN_TO_BE_DISABLE_REPEAT_TAP = 0x66
    case CAUTION_FOR_ENABLING_2_DEVICES_CONNECTION_WITH_LDAC = 0x70
    case CAUTION_FOR_CHANGING_TO_QUALITY_PRIOR_CONNECTION_MODE_WITH_2_DEVICES_CONNECTION = 0x71
    case CAUTION_FOR_CONNECTED_2_DEVICES_IN_BACKGROUND_WITH_LDAC = 0x72
    case WARNING_FOR_CHANGING_TO_LDAC_990_WITH_2_DEVICES_CONNECTION = 0x73
    case DISCONNECT_CAUSED_BY_CHANGE_CLASSIC_AUDIO_SOUND_QUALITY_PRIOR_FROM_LE_AUDIO = 0x74
    case DISCONNECT_CAUSED_BY_CHANGE_CLASSIC_AUDIO_CONNECTION_QUALITY_PRIOR_FROM_LE_AUDIO = 0x75
    case DISCONNECT_CAUSED_BY_CHANGE_CLASSIC_AUDIO_SOUND_QUALITY_PRIOR = 0x76
    case DISCONNECT_CAUSED_BY_CHANGE_CLASSIC_AUDIO_CONNECTION_QUALITY_PRIOR = 0x77
    case CAUTION_FOR_TV_SOUND_BOOSTER_SETTING_ON = 0x80
    case CAUTION_FOR_TV_SOUND_BOOSTER_SETTING_OFF = 0x81
    case CAUTION_FOR_SETTINGS_STAMINA_FROM_ON_TO_OFF = 0x82
    case CAUTION_FOR_SETTINGS_STAMINA_FROM_ON_TO_OFF_NO_LIGHTING_MODE = 0x83
    case CAUTION_FOR_SETTINGS_STAMINA_FROM_OFF_TO_ON = 0x84
    case CAUTION_FOR_SETTINGS_STAMINA_FROM_OFF_TO_ON_NO_LIGHTING_MODE = 0x85
    case CAUTION_FOR_SETTINGS_SOUND_EFFECT_ON_STAMINA_ON = 0x86
    case CAUTION_FOR_SETTINGS_SOUND_EFFECT_ON_STAMINA_ON_NO_LIGHTING = 0x87
    case CAUTION_FOR_SETTINGS_LIGHTING_MODE_ON_WHEN_STAMINA_ON = 0x88
    case CAUTION_FOR_DIABLING_BGM_MODE = 0x90
    case CAUTION_FOR_USB_SUBMERSION_MONITOR_DURING_NOT_CHARGING = 0x91
    case CAUTION_FOR_USB_SUBMERSION_MONITOR_DURING_CASE_IN = 0x92
    case TURN_KEY_EQ_SUCCESS = 0x93
}

public enum AlertFlexibleMessageType: UInt8, Sendable {
    case BATTERY_CONSUMPTION_INCREASE_DUE_TO_SIMULTANEOUS_3_SETTINGS = 0x00
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_MULTI_POINT = 0x01
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_VOICE_ASSISTANT = 0x02
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_GATT = 0x03
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_GATT_WITHOUT_REBOOT = 0x04
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_GATT_NO_RIGHT_SIDE_LIMITATION = 0x05
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_GATT_WITHOUT_REBOOT_NO_RIGHT_SIDE_LIMITATION = 0x06
    case BATTERY_CONSUMPTION_INCREASE_DUE_TO_SIMULTANEOUS_3_SETTINGS_REPLY_CONFIMATION = 0x07
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_BGM_MODE = 0x08
    case CAUTION_FOR_FEATURES_EXCLUSIVE_TO_EQ = 0x09
    case CAUTION_FOR_FUNCTIONS_THAT_ARE_EXCLUSIVE_WITH_BT_STANDBY_OFF = 0x0A
    case BATTERY_CONSUMPTION_INCREASE_DUE_TO_ALL_SETTING_ACTIVATE = 0x0B
    case DISCONNECT_CAUSED_BY_ENTER_PAIRING_MODE_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION = 0x0C
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION = 0x0D
    case DISCONNECT_CAUSED_BY_CHANGING_CONNECTION_STANDBY_MODE_CLASSIC_ONLY = 0x0E
    case DISCONNECT_CAUSED_BY_CHANGING_CONNECTION_STANDBY_MODE_LE_AUDIO_CLASSIC = 0x0F
    case DISCONNECT_CAUSED_BY_CHANGE_CONNECTION_TO_LE_AUDIO_WITH_FOLLOWING_FOR_LE_AUDIO_LIMITATION = 0x11
}

public enum VoiceAssistantType: UInt8, Sendable {
    case GOOGLE_ASSISTANT = 0x00
    case AMAZON_ALEXA = 0x01
    case TENCENT_XIAOWEI = 0x02
}

public enum ConfirmationType: UInt8, Sendable {
    case CONFIRMED = 0x00
    case CONFIRMED_DONT_SHOW_AGAIN = 0x01
}

public enum AlertAction: UInt8, Sendable {
    case NEGATIVE = 0x00
    case POSITIVE = 0x01
}

public enum VibrationType: UInt8, Sendable {
    case NO_PATTERN_SPECIFIED = 0x00
}

public enum AlertMessageTypeWithLeftRightSelection: UInt8, Sendable {
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_ASSIGNABLE_BUTTON = 0x00
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_ASSIGNABLE_SENSOR = 0x01
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_WITHOUT_REBOOT_ASSIGNABLE_BUTTON = 0x02
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_WITHOUT_REBOOT_ASSIGNABLE_SENSOR = 0x03
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_WITH_SVA_ASSIGNABLE_BUTTON = 0x04
    case CAUTION_FOR_CHANGE_VOICE_ASSISTANT_WITH_SVA_ASSIGNABLE_SENSOR = 0x05
}

public enum AlertLeftRightAction: UInt8, Sendable {
    case NEGATIVE = 0x00
    case LEFT = 0x01
    case RIGHT = 0x02
}

public enum AlertActionType: UInt8, Sendable {
    case CONFIRMATION_ONLY = 0x00
    case POSITIVE_NEGATIVE = 0x01
    case POSITIVE_CONFIRMATION_WITH_REPLY = 0x02
}

public enum DefaultSelectedLeftRightValue: UInt8, Sendable {
    case LEFT = 0x00
    case RIGHT = 0x01
}

public enum PlayInquiredType: UInt8, Sendable {
    case PLAYBACK_CONTROL_WITH_CALL_VOLUME_ADJUSTMENT = 0x1
    case PLAYBACK_CONTROL_WITH_CALL_VOLUME_ADJUSTMENT_AND_FUNCTION_CHANGE = 0x2
    case PLAYBACK_CONTROL_WITH_FUNCTION_CHANGE = 0x3
    case MUSIC_VOLUME = 0x20
    case CALL_VOLUME = 0x21
    case MUSIC_VOLUME_WITH_MUTE = 0x30
    case CALL_VOLUME_WITH_MUTE = 0x31
    case PLAY_MODE = 0x40
}

public enum PlaybackStatus: UInt8, Sendable {
    case UNSETTLED = 0x00
    case PLAY = 0x01
    case PAUSE = 0x02
    case STOP = 0x03
}

public enum MusicCallStatus: UInt8, Sendable {
    case MUSIC = 0x0
    case CALL = 0x1
}

public enum PlaybackControl: UInt8, Sendable {
    case KEY_OFF = 0x00
    case PAUSE = 0x01
    case TRACK_UP = 0x02
    case TRACK_DOWN = 0x03
    case GROUP_UP = 0x04
    case GROUP_DOWN = 0x05
    case STOP = 0x06
    case PLAY = 0x07
    case FAST_FORWARD = 0x08
    case FAST_REWIND = 0x09
}

public enum PlaybackNameStatus: UInt8, Sendable {
    case UNSETTLED = 0
    case NOTHING = 1
    case SETTLED = 2
}

public enum PlayMode: UInt8, Sendable {
    case PLAY_MODE_OFF = 0x00
    case PLAY_FOLDER = 0x01
    case REPEAT_ALL = 0x02
    case REPEAT_FOLDER = 0x03
    case REPEAT_TRACK = 0x04
    case SHUFFLE_ALL = 0x05
}

public enum GsInquiredType: UInt8, Sendable {
    case GENERAL_SETTING1 = 0xD1
    case GENERAL_SETTING2 = 0xD2
    case GENERAL_SETTING3 = 0xD3
    case GENERAL_SETTING4 = 0xD4
}

public enum GsSettingType: UInt8, Sendable {
    case BOOLEAN_TYPE = 0x00
    case LIST_TYPE = 0x01
}

public enum GsSettingValue: UInt8, Sendable {
    case ON = 0x00
    case OFF = 0x01
}

public enum DisplayLanguage: UInt8, Sendable {
    case UNDEFINED_LANGUAGE = 0x00
    case ENGLISH = 0x01
    case FRENCH = 0x02
    case GERMAN = 0x03
    case SPANISH = 0x04
    case ITALIAN = 0x05
    case PORTUGUESE = 0x06
    case DUTCH = 0x07
    case SWEDISH = 0x08
    case FINNISH = 0x09
    case RUSSIAN = 0x0A
    case JAPANESE = 0x0B
    case SIMPLIFIED_CHINESE = 0x0C
    case BRAZILIAN_PORTUGUESE = 0x0D
    case TRADITIONAL_CHINESE = 0x0E
    case KOREAN = 0x0F
    case TURKISH = 0x10
}

public enum GsStringFormat: UInt8, Sendable {
    case RAW_NAME = 0x00
    case ENUM_NAME = 0x01
}

public enum AudioInquiredType: UInt8, Sendable {
    case CONNECTION_MODE = 0x00
    case UPSCALING = 0x01
    case CONNECTION_MODE_WITH_LDAC_STATUS = 0x02
    case BGM_MODE = 0x03
    case UPMIX_CINEMA = 0x04
    case CONNECTION_MODE_CLASSIC_AUDIO_LE_AUDIO = 0x05
    case VOICE_CONTENTS = 0x06
    case SOUND_LEAKAGE_REDUCTION = 0x07
    case LISTENING_OPTION_ASSIGN_CUSTOMIZABLE = 0x08
    case BGM_MODE_AND_ERRORCODE = 0x09
    case UPMIX_SERIES = 0x0A
}

public enum PriorMode: UInt8, Sendable {
    case SOUND_QUALITY_PRIOR = 0x00
    case CONNECTION_QUALITY_PRIOR = 0x01
    case LOW_LATENCY_PRIOR_BETA = 0x02
}

public enum UpscalingTypeAutoOff: UInt8, Sendable {
    case OFF = 0x00
    case AUTO = 0x01
}

public enum RoomSize: UInt8, Sendable {
    case SMALL = 0x00
    case MIDDLE = 0x01
    case LARGE = 0x02
}

public enum ListeningOptionAssignCustomizableItem: UInt8, Sendable {
    case STANDARD = 0x00
    case BGM = 0x01
    case UPMIX_CINEMA = 0x02
    case UPMIX_GAME = 0x03
    case UPMIX_MUSIC = 0x04
}

public enum UpmixItemId: UInt8, Sendable {
    case NONE = 0x00
    case CINEMA = 0x01
    case GAME = 0x02
    case MUSIC = 0x03
}

public enum SwitchingStream: UInt8, Sendable {
    case NONE = 0x00
    case LE_AUDIO = 0x01
    case CLASSIC_AUDIO = 0x02
}

public enum UpscalingType: UInt8, Sendable {
    case DSEE_HX = 0x00
    case DSEE = 0x01
    case DSEE_HX_AI = 0x02
    case DSEE_ULTIMATE = 0x03
}

public enum SystemInquiredType: UInt8, Sendable {
    case VIBRATOR = 0x00
    case PLAYBACK_CONTROL_BY_WEARING = 0x01
    case SMART_TALKING_MODE_TYPE1 = 0x02
    case ASSIGNABLE_SETTINGS = 0x03
    case VOICE_ASSISTANT_SETTINGS = 0x04
    case VOICE_ASSISTANT_WAKE_WORD = 0x05
    case WEARING_STATUS_DETECTOR = 0x06
    case EARPIECE_SELECTION = 0x07
    case CALL_SETTINGS = 0x08
    case RESET_SETTINGS = 0x09
    case AUTO_VOLUME = 0x0A
    case FACE_TAP_TEST_MODE = 0x0B
    case SMART_TALKING_MODE_TYPE2 = 0x0C
    case QUICK_ACCESS = 0x0D
    case ASSIGNABLE_SETTINGS_WITH_LIMITATION = 0x0E
    case HEAD_GESTURE_ON_OFF = 0x0F
    case HEAD_GESTURE_TRAINING = 0x10
}

public enum Preset: UInt8, Sendable {
    case AMBIENT_SOUND_CONTROL = 0x00
    case VOLUME_CONTROL = 0x10
    case PLAYBACK_CONTROL = 0x20
    case TRACK_CONTROL = 0x21
    case PLAYBACK_CONTROL_VOICE_ASSISTANT_LIMITATION = 0x22
    case VOICE_RECOGNITION = 0x30
    case GOOGLE_ASSIST = 0x31
    case AMAZON_ALEXA = 0x32
    case TENCENT_XIAOWEI = 0x33
    case MS = 0x34
    case AMBIENT_SOUND_CONTROL_QUICK_ACCESS = 0x35
    case QUICK_ACCESS = 0x36
    case TENCENT_XIAOWEI_Q_MSC = 0x37
    case TEAMS = 0x38
    case GOOGLE_ASSISTANT_WITH_AVAILABLE_ONLY_ON_BT_CLASSIC_CONNECTION_CAUTION = 0x39
    case AMAZON_ALEXA_WITH_AVAILABLE_ONLY_ON_BT_CLASSIC_CONNECTION_CAUTION = 0x40
    case TENCENT_XIAOWEI_WITH_AVAILABLE_ONLY_ON_BT_CLASSIC_CONNECTION_CAUTION = 0x41
    case QUICK_ACCESS_WITH_AVAILABLE_ONLY_ON_BT_CLASSIC_CONNECTION_CAUTION = 0x42
    case AMBIENT_SOUND_CONTROL_QUICK_ACCESS_WITH_AVAILABLE_ONLY_ON_BT_CLASSIC_CONNECTION_CAUTION = 0x43
    case TENCENT_XIAOWEI_Q_MSC_WITH_AVAILABLE_ONLY_ON_BT_CLASSIC_CONNECTION_CAUTION = 0x44
    case AMBIENT_SOUND_CONTROL_MIC = 0x45
    case LISTENING_MODE_QUICK_ACCESS = 0x46
    case CHAT_MIX = 0x70
    case CUSTOM1 = 0x71
    case CUSTOM2 = 0x72
    case NO_FUNCTION = 0xFF
}

public enum VoiceAssistant: UInt8, Sendable {
    case VOICE_RECOGNITION = 0x30
    case GOOGLE_ASSISTANT = 0x31
    case AMAZON_ALEXA = 0x32
    case TENCENT_XIAOWEI = 0x33
    case SONY_VOICE_ASSISTANT = 0x34
    case VOICE_ASSISTANT_ENABLED_IN_OTHER_DEVICE = 0x3F
    case NO_FUNCTION = 0xFF
}

public enum EarpieceFittingDetectionOperationStatus: UInt8, Sendable {
    case DETECTION_IS_NOT_STARTED = 0x00
    case DETECTION_STARTED = 0x01
    case DETECTION_COMPLETED_SUCCESSFULLY = 0x02
    case DETECTION_COMPLETED_UNSUCCESSFULLY = 0x03
}

public enum EarpieceFittingDetectionOperationErrorCode: UInt8, Sendable {
    case NO_ERROR = 0x00
    case LEFT_CONNECTION_ERROR = 0x01
    case RIGHT_CONNECTION_ERROR = 0x02
    case FUNCTION_UNAVAILABLE_ERROR = 0x03
    case LEFT_FITTING_ERROR = 0x04
    case RIGHT_FITTING_ERROR = 0x05
    case BOTH_FITTING_ERROR = 0x06
    case MEASURING_ERROR = 0x07
}

public enum EarpieceSeries: UInt8, Sendable {
    case OTHER = 0x00
    case POLYURETHANE = 0x01
    case HYBRID = 0x02
    case SOFT_FITTING_FOR_LINKBUDS_FIT = 0x03
    case NOT_DETERMINED = 0xFF
}

public enum EarpieceSize: UInt8, Sendable {
    case SS = 0x00
    case S = 0x01
    case M = 0x02
    case L = 0x03
    case LL = 0x04
    case NOT_DETERMINED = 0xFF
}

public enum EarpieceFittingDetectionOperation: UInt8, Sendable {
    case DETECTION_START = 0x00
    case DETECTION_CANCEL = 0x01
    case DETECTION_START_FORCEFUL = 0x02
}

public enum ResetType: UInt8, Sendable {
    case SETTINGS_ONLY = 0x00
    case FACTORY_RESET = 0x01
}

public enum ResetResult: UInt8, Sendable {
    case SUCCESS = 0x00
    case ERROR_CONNECTION_LEFT = 0x01
    case ERROR_CONNECTION_RIGHT = 0x02
}

public enum FaceTapKey: UInt8, Sendable {
    case LEFT_SIDE_KEY = 0x00
    case RIGHT_SIDE_KEY = 0x01
}

public enum FaceTapAction: UInt8, Sendable {
    case DOUBLE_TAP = 0x00
    case TRIPLE_TAP = 0x01
}

public enum HeadGestureAction: UInt8, Sendable {
    case NOD = 0x00
    case SWING = 0x01
}

public enum DetectSensitivity: UInt8, Sendable {
    case AUTO = 0x00
    case HIGH = 0x01
    case LOW = 0x02
}

public enum ModeOutTime: UInt8, Sendable {
    case FAST = 0x00
    case MID = 0x01
    case SLOW = 0x02
    case NONE = 0x03
}

public enum Action: UInt8, Sendable {
    case SINGLE_TAP = 0x00
    case DOUBLE_TAP = 0x01
    case TRIPLE_TAP = 0x02
    case REPEAT_TAP = 0x03
    case SINGLE_TAP_AND_HOLD = 0x10
    case DOUBLE_TAP_AND_HOLD = 0x11
    case LONG_PRESS_THEN_ACTIVATE = 0x21
    case LONG_PRESS_DURING_ACTIVATE = 0x22
}

public enum EarpieceFittingDetectionResult: UInt8, Sendable {
    case GOOD = 0x00
    case POOR = 0x01
}

public enum CallSettingsTestSoundControl: UInt8, Sendable {
    case START = 0x00
}

public enum CallSettingsTestSoundControlAck: UInt8, Sendable {
    case ACK = 0x00
}

